// MACHINE GENERATED BY 'go generate' COMMAND; DO NOT EDIT

package extracticon

import "unsafe"
import "syscall"

var _ unsafe.Pointer

var (
	modshell32  = syscall.NewLazyDLL("shell32.dll")
	moduser32   = syscall.NewLazyDLL("user32.dll")
	modgdi32    = syscall.NewLazyDLL("gdi32.dll")
	modkernel32 = syscall.NewLazyDLL("kernel32.dll")

	procSHGetFileInfoW           = modshell32.NewProc("SHGetFileInfoW")
	procGetDC                    = moduser32.NewProc("GetDC")
	procReleaseDC                = moduser32.NewProc("ReleaseDC")
	procDeleteDC                 = modgdi32.NewProc("DeleteDC")
	procDeleteObject             = modgdi32.NewProc("DeleteObject")
	procGetIconInfo              = moduser32.NewProc("GetIconInfo")
	procCreateIconFromResourceEx = moduser32.NewProc("CreateIconFromResourceEx")
	procLoadLibraryExW           = modkernel32.NewProc("LoadLibraryExW")
	procLoadResource             = modkernel32.NewProc("LoadResource")
	procLockResource             = modkernel32.NewProc("LockResource")
	procFindResourceExW          = modkernel32.NewProc("FindResourceExW")
	procFindResourceW            = modkernel32.NewProc("FindResourceW")
	procSizeofResource           = modkernel32.NewProc("SizeofResource")
	procCreateCompatibleDC       = modgdi32.NewProc("CreateCompatibleDC")
	procCreateDIBSection         = modgdi32.NewProc("CreateDIBSection")
	procSelectObject             = modgdi32.NewProc("SelectObject")
	procDrawIconEx               = moduser32.NewProc("DrawIconEx")
	procExtractIconExW           = modshell32.NewProc("ExtractIconExW")
	procDestroyIcon              = moduser32.NewProc("DestroyIcon")
)

func shGetFileInfo(pszPath *uint16, dwFileAttributes uint32, psfi uintptr, cbFileInfo uint32, uFlags uint32) (i uintptr, err error) {
	r0, _, e1 := syscall.Syscall6(procSHGetFileInfoW.Addr(), 5, uintptr(unsafe.Pointer(pszPath)), uintptr(dwFileAttributes), uintptr(psfi), uintptr(cbFileInfo), uintptr(uFlags), 0)
	i = uintptr(r0)
	if i == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func getDC(hWnd Handle) (h Handle, err error) {
	r0, _, e1 := syscall.Syscall(procGetDC.Addr(), 1, uintptr(hWnd), 0, 0)
	h = Handle(r0)
	if h == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func releaseDC(hWnd Handle, hDC Handle) (ret int, err error) {
	r0, _, e1 := syscall.Syscall(procReleaseDC.Addr(), 2, uintptr(hWnd), uintptr(hDC), 0)
	ret = int(r0)
	if ret == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func deleteDC(hdc Handle) (b int, err error) {
	r0, _, e1 := syscall.Syscall(procDeleteDC.Addr(), 1, uintptr(hdc), 0, 0)
	b = int(r0)
	if b == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func deleteObject(hObject Handle) (b int, err error) {
	r0, _, e1 := syscall.Syscall(procDeleteObject.Addr(), 1, uintptr(hObject), 0, 0)
	b = int(r0)
	if b == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func getIconInfo(icon Handle, pinfo uintptr) (b int, err error) {
	r0, _, e1 := syscall.Syscall(procGetIconInfo.Addr(), 2, uintptr(icon), uintptr(pinfo), 0)
	b = int(r0)
	if b == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func createIconFromResourceEx(pbIconBits *byte, cbIconBits int, fIcon bool, dwVersion int, cxDesired int32, cyDesired int32, flags uint32) (h Handle, err error) {
	var _p0 uint32
	if fIcon {
		_p0 = 1
	} else {
		_p0 = 0
	}
	r0, _, e1 := syscall.Syscall9(procCreateIconFromResourceEx.Addr(), 7, uintptr(unsafe.Pointer(pbIconBits)), uintptr(cbIconBits), uintptr(_p0), uintptr(dwVersion), uintptr(cxDesired), uintptr(cyDesired), uintptr(flags), 0, 0)
	h = Handle(r0)
	if h == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func loadLibraryEx(filename *uint16, file Handle, flags uint32) (handle Handle, err error) {
	r0, _, e1 := syscall.Syscall(procLoadLibraryExW.Addr(), 3, uintptr(unsafe.Pointer(filename)), uintptr(file), uintptr(flags))
	handle = Handle(r0)
	if handle == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func loadResource(hModule Handle, hResInfo Handle) (h Handle, err error) {
	r0, _, e1 := syscall.Syscall(procLoadResource.Addr(), 2, uintptr(hModule), uintptr(hResInfo), 0)
	h = Handle(r0)
	if h == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func lockResource(hResData Handle) (u uintptr, err error) {
	r0, _, e1 := syscall.Syscall(procLockResource.Addr(), 1, uintptr(hResData), 0, 0)
	u = uintptr(r0)
	if u == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func findResourceEx(hModule Handle, lpType uintptr, lpName uintptr, wLanguage int) (h Handle) {
	r0, _, _ := syscall.Syscall6(procFindResourceExW.Addr(), 4, uintptr(hModule), uintptr(lpType), uintptr(lpName), uintptr(wLanguage), 0, 0)
	h = Handle(r0)
	return
}

func findResource(hModule Handle, lpName uintptr, lpType uintptr) (h Handle, err error) {
	r0, _, e1 := syscall.Syscall(procFindResourceW.Addr(), 3, uintptr(hModule), uintptr(lpName), uintptr(lpType))
	h = Handle(r0)
	if h == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func sizeofResource(hModule Handle, hResInfo Handle) (i int) {
	r0, _, _ := syscall.Syscall(procSizeofResource.Addr(), 2, uintptr(hModule), uintptr(hResInfo), 0)
	i = int(r0)
	return
}

func createCompatibleDC(hdc Handle) (h Handle, err error) {
	r0, _, e1 := syscall.Syscall(procCreateCompatibleDC.Addr(), 1, uintptr(hdc), 0, 0)
	h = Handle(r0)
	if h == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func createDIBSection(hdc Handle, pbmih uintptr, iUsage uint32, ppvBits *unsafe.Pointer, hSection Handle, dwOffset uint32) (h Handle, err error) {
	r0, _, e1 := syscall.Syscall6(procCreateDIBSection.Addr(), 6, uintptr(hdc), uintptr(pbmih), uintptr(iUsage), uintptr(unsafe.Pointer(ppvBits)), uintptr(hSection), uintptr(dwOffset))
	h = Handle(r0)
	if h == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func selectObject(hdc Handle, hgdiobj Handle) (h Handle, err error) {
	r0, _, e1 := syscall.Syscall(procSelectObject.Addr(), 2, uintptr(hdc), uintptr(hgdiobj), 0)
	h = Handle(r0)
	if h == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func drawIconEx(hdc Handle, xLeft int32, yTop int32, hIcon Handle, cxWidth int32, cyWidth int32, istepIfAniCur uint32, hbrFlickerFreeDraw Handle, diFlags uint32) (b int, err error) {
	r0, _, e1 := syscall.Syscall9(procDrawIconEx.Addr(), 9, uintptr(hdc), uintptr(xLeft), uintptr(yTop), uintptr(hIcon), uintptr(cxWidth), uintptr(cyWidth), uintptr(istepIfAniCur), uintptr(hbrFlickerFreeDraw), uintptr(diFlags))
	b = int(r0)
	if b == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func extractIconEx(lpszFile *uint16, nIconIndex int, phiconLarge *Handle, phiconSmall *Handle, nIcons int) (i int, err error) {
	r0, _, e1 := syscall.Syscall6(procExtractIconExW.Addr(), 5, uintptr(unsafe.Pointer(lpszFile)), uintptr(nIconIndex), uintptr(unsafe.Pointer(phiconLarge)), uintptr(unsafe.Pointer(phiconSmall)), uintptr(nIcons), 0)
	i = int(r0)
	if i == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func destroyIcon(hIcon Handle) (b bool, err error) {
	r0, _, e1 := syscall.Syscall(procDestroyIcon.Addr(), 1, uintptr(hIcon), 0, 0)
	b = r0 != 0
	if b == false {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}
